language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "sfarias051-github"
    token:
      secure: ${SONAR_TOKEN}

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
